// templates/pdf/_font_inject.js — auto-generated by scripts/gen_font_css.py
// DO NOT EDIT MANUALLY. Re-run the script after changing fonts or FONT_CN.
//
// Usage in render.mjs:
//   import { FONT_CSS } from '../../templates/pdf/_font_inject.js';
//   await page.addStyleTag({ content: FONT_CSS });

import path from 'path';
import { fileURLToPath } from 'url';

const _d = path.dirname(fileURLToPath(import.meta.url));
const _f = (p) => 'file://' + path.resolve(_d, '..', '..', 'fonts', p);

export const FONT_CSS = [
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:250;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_35_Thin_35_Thin.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:300;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_45_Light_45_Light.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:400;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_55_Regular_55_Regular.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:500;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_65_Medium_65_Medium.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:600;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_75_SemiBold_75_SemiBold.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:700;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_55_Regular_85_Bold.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:800;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_95_ExtraBold_95_ExtraBold.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:900;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_105_Heavy_105_Heavy.ttf')}") format("truetype")}`,
  `@font-face{font-family:"Alibaba PuHuiTi 2.0";font-weight:1000;font-style:normal;src:url("${_f('alibaba-puhuiti/Alibaba_PuHuiTi_2.0_115_Black_115_Black.ttf')}") format("truetype")}`,
].join('');
